image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10

# cache:
#   - '%LOCALAPPDATA%/Yarn'
#   - node_modules -> yarn.lock
#   - packages/*/node_modules -> yarn.lock

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - ps: | # Install latest yarn version
      (New-Object Net.WebClient).DownloadFile("https://yarnpkg.com/latest.msi", "$env:temp\yarn.msi")
      cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart
  - node --version
  - yarn --version
  - set CI=true
  - yarn install --ignore-scripts --ignore-engines

test_script:
  - yarn run lint
  # - yarn run flow
  - yarn run build
  - yarn test
