image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 9

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules -> package.json
  - flow-typed
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - node --version
  - yarn --version
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  # NOTE: Remove this if your project is private and you don't have a paid greenkeeper account
  - yarn global add greenkeeper-lockfile@2
  - yarn install --ignore-scripts

# NOTE: Remove this if your project is private and you don't have a paid greenkeeper account
before_test:
  - greenkeeper-lockfile-update

test_script:
  - yarn run lint
  # - yarn run flow
  - yarn run build
  - yarn run test

# NOTE: Remove this if your project is private and you don't have a paid greenkeeper account
after_test: greenkeeper-lockfile-upload
